Sitenzo add sortBy navigation
awcodes/filament-quick-create pull request #39
Opened 2023-11-28 20:59 UTC by sitenzo

2023-11-29 21:07 UTC, awcodes requested changes
You missing the $sortBy property on the class. It will throw an error if ->sortBy() isn't used when registering the plugin.

```php
protected string | Closure $sortBy = 'label';
```

2023-11-29 21:07 UTC, awcodes commented on src/QuickCreatePlugin.php
> +        if(!in_array(['label','navigation'])){
You're missing the 'needle' for in_array().

```php
if(! in_array($sortBy, ['label','navigation'])){
    $sortBy = 'label';
}
```

2023-11-29 21:07 UTC, awcodes commented on README.md
> +### Sorting by recourse navigation
Should be 'resource' not 'recourse'

2023-11-29 21:07 UTC, awcodes commented on README.md
> +By default, Quick Create will sort all the displayed options by Label. This can be changed to resource navigation sort should you choose. In which case they will be displayed in the order they are di
Please fix 'de' to be 'the'

2023-11-30 20:47 UTC, sitenzo commented
Hi @awcodes,
Thanks for the feedback.

2023-12-01 14:39 UTC, awcodes approved these changes

2023-12-01 14:41 UTC, merged