Added support for registering keybindings to open the quick add dropdown component
awcodes/filament-quick-create pull request #61
Opened 2024-11-02 17:39 UTC by johntrickett86

@awcodes Managed to figure it out!

Please review and let me know your thoughts.

2024-11-02 18:10 UTC, johntrickett86 commented
@awcodes It would have been nice to add a tooltip showing keyboard shortcut but I couldn't see a clear way to achieve that using the button component.

2024-11-04 14:30 UTC, awcodes requested changes

2024-11-04 14:30 UTC, awcodes commented on resources/views/components/create-menu.blade.php
> +<div class="quick-create-component" x-data="{ dropdownOpen: false }">
```
@if($keyBindings)
    x-data="{
        toggleDropdown() {
            this.$refs.triggerButton.click()
            this.$refs.triggerButton.focus()
        }
    }"
@endif
```

2024-11-04 14:30 UTC, awcodes commented on resources/views/components/create-menu.blade.php
> +                        x-ref="triggerButton"
```
@if($keyBindings)
    x-ref="triggerButton"
    x-mousetrap.global.{{ $keyBindings }}="toggleDropdown"
@endif
```

2024-11-04 17:03 UTC, johntrickett86 commented
@awcodes Thanks for the feedback. That's been updated.

2024-11-04 18:30 UTC, awcodes approved these changes

2024-11-04 18:30 UTC, merged